### ISSUE TITLE
All files

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AZ500-AzureSecurityTechnologies.id-id#1]
All files in image folder are untranslated yet

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
Because all the image in Web, we can't fix it. Rejected.
