### ISSUE TITLE
LAB_15_Azure Sentinel.md

### ISSUE THREAD

**Issue by HienThuThiDai** [MicrosoftLearning/AZ500-AzureSecurityTechnologies.id-id#70]
English: 
Add built in and custom alerts

Current Translation:
Tambahkan peringatan bawaan dan khusus

Suggested Translation:
Tambahkan peringatan bawaan dan kustom

Description:
The word "custom" is translated "kustom" as per TB

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
Run bugfix tool and waiting for result.

**Comment by olprod** [comment]
![image](https://user-images.githubusercontent.com/16075726/183864550-220c2c6d-4503-4219-ae72-f46c2208c99e.png)
